ktor {
  deployment {
    port = 8080
    port = ${?ASTRAX_PORT}
    host = "0.0.0.0"
    host = ${?ASTRAX_HOST}
  }
  application {
    modules = [ com.astrax.server.ApplicationKt.module ]
  }
}

astrax {
  jwt {
    issuer = "astrax"
    audience = "astrax-users"
    realm = "astrax"
    secret = ${?ASTRAX_JWT_SECRET}
    ttlMillis = 86400000
  }
  database {
    jdbcUrl = ${?ASTRAX_DB_URL}
  }
}
